### PR TITLE
improves the display of text and java code

### PR DESCRIPTION
**Pull request by maverickmishra**
Plain text was getting merged with java code which has been fixed

### CODE REVIEW

**Comment by GarthDB** [comment]
@maverickmishra - who are you looking to review this?

**Comment by maverickmishra** [comment]
sent a link to @stevengill

**Comment by GarthDB** [comment]
Cool - I assigned him.  Looks like the tests are failing because wikitude changed their docs url structure. I would just ignore them for now and I'll check in with Tim again on it.

**Comment by purplecabbage** [comment]
What is the status of this? Are we merging and publishing?

We have a number of duplicates or let's call them re-affirmations :
https://github.com/phonegap/phonegap-intellij-plugin/issues/11
https://github.com/phonegap/phonegap-roadmap/issues/213

**Pull request merged**
